### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by cgy0905** [sqsong66/TMDB-Movie#1]
![image](https://github.com/sqsong66/TMDB-Movie/assets/21997262/3e0524b0-77e5-475d-9cff-8519127a3633)
项目编译提示一个文件找不到，ImageError.kt    as版本2023.1.1 支持的agp最高是8.1.3 我把你的这个改了，其他地方未动，编译不起

**Comment by sqsong66** [comment]
那个文件是在这个包下面的：com.tmdb.movie.component.myiconpack，你看一下你的工程目录中有没有ImgErro.kt这个文件，我看Github的目录中是有的。

**Comment by sqsong66** [comment]
我在我的AS中AGP改成8.2.0也可以编译通过

**Comment by cgy0905** [comment]
我试一下
&nbsp;


Mic.Chen
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月19日(星期五) 上午10:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [sqsong66/TMDB-Movie] 编译出错 (Issue #1)





 
我在我的AS中AGP改成8.2.0也可以编译通过
